collections:
  diensten:
    output: true
    permalink: /:collection/:name
  methodes:
    output: true
    permalink: /:collection/:name
  projecten:
    output: true
    permalink: /:collection/:name
#  materialen:
#    output: true
#    permalink: /:collection/:name/
#  peeps:
#    output: true
#    permalink: /:collection/:name/
#  good-public-tech:
#    output: true
#    permalink: /:collection/:name/