collections:
  diensten:
    output: true
    permalink: /:collection/:name/
    order:
      - advies.html
      - innovatie.html
      - apps.html
      - labs.html
#  methodes:
#    output: true
#    permalink: /:collection/:name/
  projecten:
    output: true
    permalink: /:collection/:name/
#  materialen:
#    output: true
#    permalink: /:collection/:name/